### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Kalman98** [ParkerMc/RA1#2]
I will gather up and keep a list of things that need to be worked on here, using the handy Task Lists feature of GitHub.

**Comment by ParkerMc** [comment]
Good idea can you use the projects feature or do I need to add something?

**Comment by Kalman98** [comment]
I don't really know how the Projects feature works, to be honest. Maybe it would work better than here, I will try to figure it out. If it doesn't, sadly, you just ruined this issue. 😞 The task list has to be in the first comment in order for it to render in the Issues list.

**Comment by Kalman98** [comment]
Okay, I think the Projects will in fact work better for this purpose. Case closed. 👍
